/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pakar.component;

import com.pakar.koneksi.koneksi;
import com.pakar.form.Form1;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

// PopupFormEditPegawai
/**
 *
 * @author Akbar Ramadhani Firdaus
 */
public class PopupFormEditPegawai extends javax.swing.JDialog {

    /**
     * Creates new form PopupInsertPegawai
     */

    private void clear(){
        txt_nik.setText(null);
        txt_nama.setText(null);
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        txt_alamat.setText(null);
        txt_nohp.setText(null);
        warning.setText(null);
        warning1.setText(null);
    }
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
//    private void initiateDropdownPekerjaan() {
//        try {
//            Connection c = koneksi.configDB();
//            Statement s = c.createStatement();
//            String sql = "SELECT * FROM `jabatan`";
//            ResultSet rs = s.executeQuery(sql);
//            while (rs.next()) {
////                supplier_txt.
//                jComboBox2.addItem(rs.getString("id"));
//            }
//        } catch (SQLException e) {
////            MyFunction.showErrorMessage(e.getMessage(), "Error!");
//        }
//    }

//    private void initiateDropdownJk() {
//        try {
//            Connection c = koneksi.configDB();
//            Statement s = c.createStatement();
//            String sql = "SELECT * FROM `karyawan`";
//            ResultSet rs = s.executeQuery(sql);
//            while (rs.next()) {
////                supplier_txt.
//                jComboBox1.addItem(rs.getString("jenis_kelamin"));
//            }
//        } catch (SQLException e) {
////            MyFunction.showErrorMessage(e.getMessage(), "Error!");
//        }
//    }
    String id = null;
    public PopupFormEditPegawai(JFrame pfep, String id) {
        super(pfep, true);
        initComponents();
        this.id = id;
        System.out.println(id);
        clear();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 40, 40));
        txt_nik.setBackground(new java.awt.Color(0,0,0,1));
        txt_nama.setBackground(new java.awt.Color(0,0,0,1));
        txt_alamat.setBackground(new java.awt.Color(0,0,0,1));
        txt_nohp.setBackground(new java.awt.Color(0,0,0,1));
        txtcard_code.setBackground(new java.awt.Color(0,0,0,1));
        warning.setBackground(new java.awt.Color(0,0,0,1));
        warning1.setBackground(new java.awt.Color(0,0,0,1));
//        initiateDropdownJk();
//        initiateDropdownPekerjaan();
        getTampil();
    }
    private void getTampil(){
        try{
            String sql = "select * from karyawan where nik = '"+ id+"'";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
            if(rs.next()){
                txt_nik.setText(rs.getString(1));
                txt_nama.setText(rs.getString(2));
                jComboBox2.setSelectedItem(rs.getString(3));
                txt_alamat.setText(rs.getString(5));
                jComboBox1.setSelectedItem(rs.getString(4));
                txt_nohp.setText(rs.getString(6));
                txtcard_code.setText(rs.getString(7));
            }
        }catch(SQLException ex){
        
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        warning1 = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        txt_alamat = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_nik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rounded3 = new com.pakar.component.Rounded();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcard_code = new javax.swing.JTextField();
        warning = new javax.swing.JTextField();
        rounded2 = new com.pakar.component.Rounded();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(39, 211, 249));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel9.setText("____________________");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 200, -1));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel10.setText("____________________");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 40));

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel12.setText("____________________");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 40));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel13.setText("____________________");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, 30));

        warning1.setEditable(false);
        warning1.setBackground(new java.awt.Color(255, 255, 255));
        warning1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warning1.setForeground(new java.awt.Color(255, 0, 0));
        warning1.setBorder(null);
        warning1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(warning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, 20));

        txt_nohp.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        txt_nohp.setBorder(null);
        txt_nohp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nohpKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nohpKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, 40));

        jComboBox2.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guru", "Satpam", "Karyawan" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 200, 40));

        jComboBox1.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, 40));

        txt_alamat.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        txt_alamat.setBorder(null);
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 30));

        txt_nama.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        txt_nama.setBorder(null);
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 200, 30));

        txt_nik.setEditable(false);
        txt_nik.setBackground(new java.awt.Color(255, 255, 255));
        txt_nik.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        txt_nik.setBorder(null);
        txt_nik.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nikActionPerformed(evt);
            }
        });
        txt_nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nikKeyPressed(evt);
            }
        });
        getContentPane().add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 200, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel2.setText("Nama                  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel3.setText("Edit Data Pegawai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel4.setText("NIK                      :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel5.setText("Pekerjaan          :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel6.setText("Alamat               :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel7.setText("Nomor HP         :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel8.setText("Jenis Kelamin   :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 40));

        jLabel16.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("________________________________________________");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 40));

        rounded3.setBackground(new java.awt.Color(204, 204, 204));
        rounded3.setRoundBottomLeft(40);
        rounded3.setRoundBottomRight(40);
        rounded3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(64, 194, 255));
        jButton2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIMPAN");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        rounded3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        rounded3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 100, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("HAPUS");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        rounded3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 100, 30));

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel15.setText("____________________");
        rounded3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, 20));

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel14.setText("Kode ID             :");
        rounded3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtcard_code.setBackground(new java.awt.Color(255, 255, 255));
        txtcard_code.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        txtcard_code.setBorder(null);
        txtcard_code.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        rounded3.add(txtcard_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, 30));

        warning.setEditable(false);
        warning.setBackground(new java.awt.Color(255, 255, 255));
        warning.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setBorder(null);
        rounded3.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 200, -1));

        getContentPane().add(rounded3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 480, 390));

        rounded2.setBackground(new java.awt.Color(64, 194, 255));
        rounded2.setRoundBottomLeft(40);
        rounded2.setRoundBottomRight(40);
        rounded2.setRoundTopLeft(40);
        rounded2.setRoundTopRight(40);
        rounded2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel17.setText("X");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        rounded2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 20, 20));

        getContentPane().add(rounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/raven/icon/check.png"));
        try{
            String sql = "UPDATE karyawan SET nik = '"+txt_nik.getText()
            +"', nama = '"+txt_nama.getText()
            +"', jabatan = '"+jComboBox2.getSelectedItem()
            +"', jenis_kelamin = '"+jComboBox1.getSelectedItem()
            +"', alamat = '"+txt_alamat.getText()
            +"', no_hp = '"+txt_nohp.getText()
            +"', card_code = '"+txtcard_code.getText()
            +"'WHERE karyawan.nik = '"+txt_nik.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            Form1 fm1 = new Form1();
            fm1.load_table();
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update", "Pesan Pemberitahuan", JOptionPane.PLAIN_MESSAGE, icon);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Update Data Gagal"
                +e.getMessage());
        }
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_nohpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nohpKeyTyped
//        char c = evt.getKeyChar();
//        
//        if (Character.isDigit(c)) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txt_nohpKeyTyped

    private void txt_nohpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nohpKeyPressed
       String nomor_hp = txt_nohp.getText();
        
        int panjang = nomor_hp.length();
        
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txt_nohp.setEditable(false);
            warning.setText("Mohon Masukkan Angka");
        }else{
            
        
        if (evt.getKeyChar() >= '0' && evt.getKeyChar()<='9') {
            if (panjang<=13) {
                txt_nohp.setEditable(true);
            }else{
                txt_nohp.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {
                txt_nohp.setEditable(true);
            }else{
                txt_nohp.setEditable(false);
            }
        }}
    }//GEN-LAST:event_txt_nohpKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String sql = "DELETE FROM karyawan WHERE nik='"+txt_nik.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil Menghapus Data");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Form1 fm1 = new Form1();
        fm1.load_table();
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nikActionPerformed

    private void txt_nikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nikKeyPressed
        String nik = txt_nik.getText();
        
        int panjang = nik.length();
        
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txt_nik.setEditable(false);
            warning1.setText("Mohon Masukkan Angka");
        }else{
            
        
        if (evt.getKeyChar() >= '0' && evt.getKeyChar()<='9') {
            if (panjang<17) {
                txt_nik.setEditable(true);
            }else{
                txt_nik.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {
                txt_nik.setEditable(true);
            }else{
                txt_nik.setEditable(false);
            }
        }}
    }//GEN-LAST:event_txt_nikKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Form1 fm1 = new Form1();
        fm1.load_table();
    }//GEN-LAST:event_formWindowActivated

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        close();
    }//GEN-LAST:event_jLabel17MouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PopupDeleteDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PopupDeleteDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PopupDeleteDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PopupDeleteDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PopupFormEditPegawai().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.pakar.component.Rounded rounded2;
    private com.pakar.component.Rounded rounded3;
    public javax.swing.JTextField txt_alamat;
    public javax.swing.JTextField txt_nama;
    public javax.swing.JTextField txt_nik;
    public javax.swing.JTextField txt_nohp;
    public javax.swing.JTextField txtcard_code;
    public javax.swing.JTextField warning;
    public javax.swing.JTextField warning1;
    // End of variables declaration//GEN-END:variables
}
